# Generated by Django 5.1.6 on 2025-02-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_phone_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='photo_url',
        ),
    ]
